spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcarshop?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate.auto_quote_keyword: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        default-page-size: 10
        default-page-number: 0
        one-indexed-parameters: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace


# http://localhost:8080/swagger-ui/index.html