spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcarshop?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate.auto_quote_keyword: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

